general.import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

#[Appearance]
#opacity = 1.0
#blur = true
decorations = "Transparent"

[window]
dimensions = { columns = 110, lines = 26 }
padding = { x = 25, y = 5 }
dynamic_padding = true
startup_mode = "Windowed"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15

